### ISSUE TITLE
Store the best epoch in checkpoint file

### ISSUE THREAD

**Issue by BerndDoser** [HITS-AIN/Spherinator#19]
Trainer callback [ModelCheckpoint](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html)

Add to config.yaml:
```yaml
trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: train_loss
        filename: "{epoch}-{train_loss:.2f}"
        save_top_k: 1
        mode: min
        every_n_epochs: 1
```
